### ISSUE TITLE
check against RX overflow in rftxrx_isr?

### ISSUE THREAD

**Issue by ecc1** [ps2/subg_rfspy#22]
I don't see any check that radio_rx_buf_len hasn't exceeded MAX_PACKET_LEN when you read an incoming byte.  If you're getting a lot of noise, isn't it possible that it will overrun while you're still looping in get_packet_and_write_to_serial?

**Comment by ps2** [comment]
Didn't see this until now, for some reason, but yes, it looks like that's possible.  Thanks for the heads up.
