### ISSUE TITLE
When using the command "openaps use pump mmtune", the help text does not appear

### ISSUE THREAD

**Issue by andrew-warrington** [ps2/subg_rfspy#24]
The file mmtune.py includes help text explaining required arguments. This text does not appear when using "openaps use pump mmtune" command. 

This may possibly be an openaps topic rather than a mmtune topic.

Help text:
    print "Usage: mmtune.py /dev/ttyMFD1 pumpserial [radio_locale]"
    print "Radio locale defaults to 'US'. Set to 'WW' for other countries"

**Comment by oskarpearson** [comment]
This can be closed - I've re-created it against the MMeowlink repo.

**Comment by andrew-warrington** [comment]
Agreed - bug posted in wrong repository.
